
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: next_employees_postgres_db

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DATABASE_URL=$DATABASE_URL
    ports:
      - "3000:3000"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - db

volumes:
  db_data: